server:
  redis_host: '107.151.172.213'
  redis_port: 10070
  redis_delay: 5
  modbus_port: 502
  modbus_delay: 5
scrept:
    设备1:
    - adr: 1    
    - A3-1A01机柜功率:
        adr: 1
        gs: '{S9E42A164}+{S9E44A164}'
        type: float   
    - A3-1A01机柜功率百分比:
        adr: 3
        gs: '({S9E42A164}+{S9E44A164})/0.03'
        type: float  
    - A3-1A01机柜功率超限80:
        adr: 2
        gs: '1 if (({S9E42A164}+{S9E44A164})/0.03)>80 else 0'
        type: int
    - A3-1A01机柜功率超限100:
        adr: 3
        gs: '1 if (({S9E42A164}+{S9E44A164})/0.03)>100 else 0'
        type: int
    设备2:
    - adr: 2
    - A3-1A02机柜功率:
        adr: 1
        gs: '{S9E42A176}+{S9E44A176}'
        type: float
    - A3-1A02机柜功率百分比:
        adr: 3
        gs: '({S9E42A176}+{S9E44A176})/0.03'
        type: float
    - A3-1A02机柜功率超限80:
        adr: 2
        gs: '1 if (({S9E42A176}+{S9E44A176})/0.03)>80 else 0'
        type: int
    - A3-1A02机柜功率超限80:
        adr: 3
        gs: '1 if (({S9E42A176}+{S9E44A176})/0.03)>100 else 0'
        type: int